import React from 'react'
import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'

const Layout = ({children}) => {
  return (
    <div>
         <Head>
        <title>Todo Apps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='container'>
        {children}
      </main>
      <Footer />
    </div>
  )
}

export default Layout